/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('../panel/plugins/console/src/components/ActionButton.vue')['default']
    ArchivePreview: typeof import('../panel/plugins/console/src/components/ArchivePreview.vue')['default']
    BetweenMenus: typeof import('../panel/plugins/console/src/components/BetweenMenus.vue')['default']
    CardPanel: typeof import('../panel/plugins/console/src/components/CardPanel.vue')['default']
    CopyButton: typeof import('../panel/plugins/console/src/components/CopyButton.vue')['default']
    DataStatistic: typeof import('../panel/plugins/console/src/components/DataStatistic.vue')['default']
    Editor: typeof import('../panel/plugins/console/src/components/Editor.vue')['default']
    Empty: typeof import('../panel/plugins/console/src/components/Empty.vue')['default']
    FadeUpAnimation: typeof import('../panel/plugins/console/src/components/FadeUpAnimation.vue')['default']
    IconBtn: typeof import('../panel/plugins/console/src/components/IconBtn.vue')['default']
    IframeBox: typeof import('../panel/plugins/console/src/components/IframeBox/index.vue')['default']
    IframeModal: typeof import('../panel/plugins/console/src/components/IframeModal/index.vue')['default']
    InnerCard: typeof import('../panel/plugins/console/src/components/InnerCard.vue')['default']
    InstallOptionButton: typeof import('../panel/plugins/console/src/components/InstallOptionButton.vue')['default']
    InstanceConfigEditor: typeof import('../panel/plugins/console/src/components/InstanceConfigEditor.vue')['default']
    KvOptionsDialog: typeof import('../panel/plugins/console/src/components/fc/KvOptionsDialog.vue')['default']
    LeftMenuBtn: typeof import('../panel/plugins/console/src/components/LeftMenuBtn.vue')['default']
    LeftMenusPanel: typeof import('../panel/plugins/console/src/components/LeftMenusPanel.vue')['default']
    LineOption: typeof import('../panel/plugins/console/src/components/LineOption.vue')['default']
    Loading: typeof import('../panel/plugins/console/src/components/Loading.vue')['default']
    OverwriteFilesPopUpContent: typeof import('../panel/plugins/console/src/components/OverwriteFilesPopUpContent.vue')['default']
    ResponsiveLayoutGroup: typeof import('../panel/plugins/console/src/components/ResponsiveLayoutGroup.vue')['default']
    RightMenu: typeof import('../panel/plugins/console/src/components/fc/RightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Style1: typeof import('../panel/plugins/console/src/components/time/Style1.vue')['default']
    Style2: typeof import('../panel/plugins/console/src/components/time/Style2.vue')['default']
    TaskLoadingDialog: typeof import('../panel/plugins/console/src/components/fc/TaskLoadingDialog.vue')['default']
    TextContainer: typeof import('../panel/plugins/console/src/components/TextContainer.vue')['default']
    UploadTaskProgress: typeof import('../panel/plugins/console/src/components/UploadTaskProgress.vue')['default']
    WarningDialog: typeof import('../panel/plugins/console/src/components/fc/WarningDialog.vue')['default']
  }
}
